### ISSUE TITLE
v2.4.10 gulp init error

### ISSUE THREAD

**Issue by huanghaiyang** [cocos-creator/cocos2d-x-lite#4308]
**node 10.24.1**

https://gitlab.cocos.net/publics/cocos2d-x-lite-external/-/archive/v24-9/cocos2d-x-lite-external-v24-9.zip 404 not found

` gulp init
[10:07:38] Using gulpfile D:\work\github\engine-native\gulpfile.js
[10:07:38] Starting 'init'...
=======================================================
==> Prepare to download external libraries!
==>  Connecting github.com:443
==>  Connecting gitlab.cocos.net:443
==>   Takes 0.290000200272s to connect to #1
==>   Takes 0.290000200272s to connect to #0
==>   Try fetch https://gitlab.cocos.net/publics/cocos2d-x-lite-external/-/archive/v24-9/cocos2d-x-lite-external-v24-9.zip
Traceback (most recent call last):
  File "download-deps.py", line 454, in <module>
    main()
  File "download-deps.py", line 448, in main
    installer = CocosZipInstaller(workpath, os.path.join(workpath, 'external', 'config.json'), os.path.join(workpath, 'external', 'version.json'), "prebuilt_libs_version", mirror)
  File "download-deps.py", line 172, in __init__
    self._url = select_fastest_url([self._url, mirror_repo_url])
  File "download-deps.py", line 129, in select_fastest_url
    u = urllib2.urlopen(url)
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1241, in https_open
    context=self._context)
  File "C:\Python27\lib\urllib2.py", line 1195, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "C:\Python27\lib\httplib.py", line 1082, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 1122, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 1078, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 894, in _send_output
    self.send(msg)
  File "C:\Python27\lib\httplib.py", line 856, in send
    self.connect()
  File "C:\Python27\lib\httplib.py", line 1303, in connect
    server_hostname=server_hostname)
  File "C:\Python27\lib\ssl.py", line 369, in wrap_socket
    _context=self)
  File "C:\Python27\lib\ssl.py", line 599, in __init__
    self.do_handshake()
  File "C:\Python27\lib\ssl.py", line 836, in do_handshake
    match_hostname(self.getpeercert(), self.server_hostname)
  File "C:\Python27\lib\ssl.py", line 288, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
CertificateError: hostname u'gitlab.cocos.net' doesn't match either of '*.cocos.com', 'cocos.com'
[10:07:39] 'init' errored after 1.11 s
[10:07:39] Error: Command failed: python download-deps.py --remove-download no
    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at execSync (D:\work\github\engine-native\gulpfile.js:58:5)
    at Gulp.<anonymous> (D:\work\github\engine-native\gulpfile.js:141:5)
    at module.exports (D:\work\github\engine-native\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (D:\work\github\engine-native\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (D:\work\github\engine-native\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (D:\work\github\engine-native\node_modules\orchestrator\index.js:134:8)
    at C:\Users\huanh\AppData\Roaming\nvm\v10.24.1\node_modules\gulp\node_modules\gulp-cli\lib\versioned\^3.7.0\index.js:79:20
    at C:\Users\huanh\AppData\Roaming\nvm\v10.24.1\node_modules\gulp\node_modules\gulp-cli\lib\shared\require-or-import.js:29:33
`

**Comment by minggo** [comment]
Sorry about it, we will fix it. 
And i am curious, why you need to download external libs yourself, they are shift with editor.

**Comment by minggo** [comment]
@PatriceJiang could you please fix it and add the PR link here?

**Comment by PatriceJiang** [comment]
The resources corresponding to gitlab.cocos.net have been taken down. I suggest you clone the repository github.com/cocos/cocos-engine-external and switch to the corresponding tag. Then, copy the repository to the external directory of the engine. If you want to download through a script, you can refer to this modification: https://github.com/cocos/engine-native/compare/master...PatriceJiang:cocos2d-x-lite:patch-8 .  @huanghaiyang
